output_dir: ~/scratch/experiments/

dataset:
  class: biomedical
  path: /home/mila/x/xhonneul/projects/NBFNet/data/biomedical_PC
  include_factgraph: yes
  fact_as_train: yes
  
task:
  class: KnowledgeGraphCompletionBio
  model:
    class: DistMult
    embedding_dim: 128
    l3_regularization: 2.0e-6
  criterion: bce
  num_negative: 512
  strict_negative: yes
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  adversarial_temperature: 1
  sample_weight: yes

optimizer:
  class: Adam
  lr: 1.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 4096

train:
  num_epoch: 100

metric: mrr
